### ISSUE TITLE
Active?

### ISSUE THREAD

**Issue by lawofthedmz** [paralax/awesome-cybersecurity-internships#38]
Is this still an ongoing project? It would be awesome!

**Comment by paralax** [comment]
yeah, although to be fair this winter I really struggled to find time and apply effort to keep it updated. normally I aim to have it ready for people to apply in the spring for summer internships.

**Comment by lawofthedmz** [comment]
Okay, sounds good!

**Comment by lawofthedmz** [comment]
Thanks
